### ISSUE TITLE
StateImageObject issue

### ISSUE THREAD

**Issue by teoprog** [jspinak/brobot#5]
I started following the tutorials here: https://jspinak.github.io/brobot/docs/tutorial-basics/states, but it seems like I can't find how to import StateImageObject. I did some research in the Brobot library and found a class StateImage that could be what I'm looking for. Could the states page have a mistake, or am I missing something?

**Comment by jspinak** [comment]
That's right, it's StateImage now :) The documentation is for the latest version on Maven Central (1.0.6) and isn't up-to-date with the latest code on GitHub. Here are some changes you might come across:

- StateImageObject is StateImage
- Image is now Pattern
- The State Structure Builder, as shown in the 2nd tutorial (Building a Visual API), is no longer available. This is because I'm developing a front end in React that will allow for building the state structure visually. This shouldn't be an issue for you, though. The first tutorial is better for getting a feel for how to use Brobot, since you code states and transitions manually. 
- You don't need to use ENUMs to give states a name, you can use a string in the State declaration: State state = new State.Builder("stateName");

There are other changes, feel free to open an issue if something is confusing.

**Comment by teoprog** [comment]
Ok, I understood the concepts, that's really well done. Thanks for the clear explanations. I have a question: once you pass the initial states, for example, at the 3rd state, if I want to define two states with the same score, how do I determine which one will be executed first?

**Comment by jspinak** [comment]
This depends on how your state graph is queried by the pathfinding algorithm. For practical purposes, assume one will be selected randomly. If you have a preference, you can specify it by changing the scores of states and transitions. Keep in mind that the scores of states and transitions affect your application in different ways. For example, changing the score of a state affects every path that includes that state. Changing the score of a transition is more specific and does not affect paths with the associated states unless the transition is also present.
