### ISSUE TITLE
How to Use Similarity and Target Offset

### ISSUE THREAD

**Issue by teoprog** [jspinak/brobot#8]
I'm working on a project using Brobot and need some guidance on how to use the similarity and target offset features when we try to click on a button. Could I have some examples on how to apply these settings in my project?

Here is how i do my click action:
```java
return action.perform(CLICK, homepage.getRoom1()).isSuccess();
```

**Comment by jspinak** [comment]
The documentation is a great place to learn how to build Brobot projects. 

In Brobot, actions are objects: https://jspinak.github.io/brobot/docs/introduction/core-features/processes-as-objects
You use the Position field to specify the click position: https://jspinak.github.io/brobot/docs/API/state%20and%20state%20objects/state-image-object

**Comment by teoprog** [comment]
I tried the method you explained, but it doesn't seem to be working:
```java
    private StateImage cookiesPopup = new StateImage.Builder()
            .addPattern("cookiesPopup")
            .setPositions(new Position(0.5, 0.5))
            .build();
```

I also tried this, but it was clicking in the middle of the image and not at the correct location:
```java
    private boolean gotoRoom1() {
        ActionOptions clickPerform = new ActionOptions.Builder()
                .setAction(CLICK)
                .setMinSimilarity(0.7)
                .setOffsetLocation(-183, 71)
                .build();

        return action.perform(clickPerform, room1.getCookies()).isSuccess();
    }
```

Could I have some help on how to fix it?

**Comment by jspinak** [comment]
When you define the StateImage you set the click position to the middle of the image: `.setPositions(new Position(0.5, 0.5))`
Position gives a percent of the width and height of the match. For example, `Position(0,1)` would click on the bottom left corner of the match and `Position(1,0)` on the top right corner.

The line `.setOffsetLocation(-183, 71)` should move the mouse after a click. See `offsetLocationBy` under https://jspinak.github.io/brobot/docs/API/data-types/actionOptions#movemouseafterclick . 
There is currently no way to set the click location with ActionOptions, although it's probably useful to have and I'll make a note to add one. I'll also make a note to make the offset variable names more descriptive. If you want more detail on all action options, check out the class file: https://github.com/jspinak/brobot/blob/main/library/src/main/java/io/github/jspinak/brobot/actions/actionOptions/ActionOptions.java . The code has the most detailed descriptions of each action.

**Comment by teoprog** [comment]
Ok, thanks for the response. It was pretty clear. However, the two codes I mentioned are separate examples. So, concerning the first one, you didn't really respond to why I got this error:
```error
Cannot resolve method 'setPositions' in 'Builder'
```

**Comment by jspinak** [comment]
`setPositions` is a `StateImage` method, but not a `StateImage.Builder` method. 

Here's how you could figure this out: 
- Your IDE probably shows you the problem when you write the code. Mine shows `.setPositions(new Position(0.5, 0.5))` in red because it's not one of the Builder methods. My IDE also gives a list of potential methods to choose after I write the period `.` and `setPositions` is not there. 
- Check the code for `StateImage`. You'll see that the method exists for `StateImage` but not for the Builder.

What you can do when you realize `setPositions` is not a Builder method:
1. Figure out what `setPositions` does by looking at the code in the `StateImage` class. You'll see that `setPositions` sets the `Position` of each `Pattern` in the `StateImage`. 
3. Look at the code for `StateImage` and see how it uses the Builder. There are multiple ways to add a `Pattern` to a `StateImage` in the Builder. One is by using a String, which we did in the MrDoob app, but you can also use a `Pattern`. 
4. Check out the `Pattern` class. It has a Builder too, and this Builder has a method `setPosition`.
5. When creating your `StateImage`, create a `Pattern` with the correct `Position` and pass it to the `StateImage.Builder`. You can do this like this:

```
private StateImage aboutText = new StateImage.Builder()  
      .addPattern(new Pattern.Builder()  
                      .setName("aboutText")  
                      .setPosition(new Position(.5, .5))  
                      .build())  
      .build();  
```

What does that mean that `setPositions` is a `StateImage` method but not a `StateImage.Builder` method? It means that you can use it once you've created the `StateImage` but not when creating it with the Builder. For example, you could write:
```
    public About(AllStatesInProjectService stateService) {
        aboutText.setPositions(new Position());
        stateService.save(state);
    }
```
I would recommend the first method, setting `Position` with `Pattern`. I will also make a note to add a `setPositions` Builder method because this is a good option to have.

**Comment by teoprog** [comment]
It doesn't seems to work. Here is my last code that was working without the positions:
```java
    private StateImage cookiesPopup = new StateImage.Builder()
            .addPattern("cookiesPopup")
            .build();
```

Now that I changed it to this:
```java
    private StateImage cookiesPopup = new StateImage.Builder()
            .addPattern(new Pattern.Builder()
                    .setName("cookiesPopup")
                    .setPosition(new Position(0.5, 0.5))
                    .build())
            .build();
```
I get the error:
```csharp
Find.FIRST Exception in thread "main" java.lang.NullPointerException: Cannot invoke "io.github.jspinak.brobot.datatypes.primitives.image.Image.sikuli()" because "this.image" is null
```
Isnt't there an error in your code. Cause it seem that the image isn't save correctly

**Comment by jspinak** [comment]
I fixed the code so you should be able to update the project and rebuild the JAR file now.
I also saw that in the unstable version, `Position` can be initiated with doubles or ints. For example, when you want the lower right corner of a region, it would be `Position = new Position(1.0, 1.0)` or `Position = new Position(100, 100)`. `Position(1,1)` will give you a position 1% to the right and down from the top left corner.

**Comment by jspinak** [comment]
I made some changes to the code to make it easier to specify the click point. You can now modify the click point within ActionOptions and set it in the StateImage builder. 

The two variables affecting the click point are
Position targetPosition: sets the position in the match as a percent of the match width and height.
Location targetOffset: adjusts the target with fixed x and y values.

In Pattern, the Builder methods are setTargetPosition and setTargetOffset.
In StateImage, the Builder methods are setPositionForAllPatterns and setOffsetForAllPatterns. Using these methods will set the position or the offset for all Pattern objects in the StateImage.

How the target is calculated: 
1. The location is calculated as the position in the region. The position gives the % of width and height of the region. (.5,.5) or (50,50) is the middle of the region.
2. The location is adjusted with the offsets.

If you set the position or offsets in a Pattern and the position or offsets in an ActionOptions object, the values in the ActionOptions will override those in the Pattern. This occurs only for the action that calls the ActionOptions object. The Pattern keeps its position and offsets for future actions. Here's an example:

```
StateImage topLeft2 = new StateImage.Builder()
        .addPattern(new Pattern.Builder()
                .setName("topLeft")
                .setTargetPosition(0,0)
                .build())
        .build();
ObjectCollection objColl2 = new ObjectCollection.Builder()
        .withImages(topLeft2)
        .withScenes("../screenshots/floranext0")
        .build();
ActionOptions actionOptions = new ActionOptions.Builder()
        .setAction(ActionOptions.Action.FIND)
        .setTargetPosition(100, 100)
        .setTargetOffset(-10,0)
        .build();
Matches matches2 = action.perform(actionOptions, objColl2);
```

The position used in this FIND operation will be (100,100) and the offset (-10,0), corresponding to the values in the ActionOptions object.
